# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-22 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alcohol_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.DecimalField(decimal_places=0, max_digits=9)),
                ('v', models.DecimalField(decimal_places=1, max_digits=1)),
            ],
        ),
        migrations.DeleteModel(
            name='alcohol',
        ),
    ]
