# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-23 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20181222_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol_1',
            name='v',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
